### PR TITLE
i think this works

### PR DESCRIPTION
**Pull request by Omay238**
dont merge yet

### CODE REVIEW

**Comment by Omay238** [comment]
aight. please merge now. when and if you do, merge [this](https://github.com/hackclub/sprig/pull/513) pr as well

**Comment by LucasHT22** [comment]
oh, remove the filename, right?

**Comment by Omay238** [comment]
yes

**Comment by LucasHT22** [comment]
before merging, I think it's better to go through a review by ced or leo or Kognise

**Comment by Omay238** [comment]
yes. thats what i wanted

**Comment by Omay238** [comment]
might reopen. pretty broken rn

**Pull request closed without merging**
